# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-18.04.1.box"
 	config.vm.hostname = "ubuntu-18.04.1.box"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

   
config.vm.provider "virtualbox" do |vb|
  vb.name = "ubuntu-1804"
  vb.memory = "1024"
  vb.cpus = 1
  end
end
